language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - gperf

sudo: false

notifications:
  email: false

os:
  - linux
  - windows
  
install:
 - git clone https://github.com/steveicarus/ivtest.git
 - export PATH=$HOME/bin:$PATH
 
before_script:
  -  autoconf
  - ./configure --prefix=$HOME

script:
  - make; make install
  - cd ivtest; perl vvp_reg.pl
